<?php 
    get_header(); 
    get_template_part('partials/splash'); 
    get_template_part('partials/reviews');
    get_template_part('partials/about');
    get_template_part('partials/products');
    get_template_part('partials/contact');
    get_footer();
?>